version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: shelterlink-postgres
    restart: unless-stopped
    env_file: ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./seed:/docker-seed  # optional
volumes:
  pgdata:
